// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	UserID string `json:"userId"`
	Text   string `json:"text"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type UpdateTodo struct {
	ID   string  `json:"id"`
	Text *string `json:"text,omitempty"`
	Done *bool   `json:"done,omitempty"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Todos []*Todo `json:"todos"`
}
